Update libsnowflakeclient for bug fixes
snowflakedb/pdo_snowflake pull request #238
Opened 2021-01-04 19:17 UTC by SimbaGithub

bug fixed in libsnowflakeclient:
Support date before 1970-01-01 on Windows: https://github.com/snowflakedb/libsnowflakeclient/pull/249
crash with named parameters more than 8: https://github.com/snowflakedb/libsnowflakeclient/pull/257

2021-01-08 22:24 UTC, sfc-gh-vreddy commented on libsnowflakeclient/deps-build/darwin/curl/lib/pkgconfig/libcurl.pc
> +prefix=/Users/bamboo/Desktop/harry/libsnowflakeclient/scripts/../deps-build/darwin/Release/curl
Isn't this Referring to a local Desktop location. This should be relative to the base directory.

2021-01-08 22:25 UTC, sfc-gh-vreddy commented on libsnowflakeclient/deps-build/darwin/curl/bin/curl-config
> +        echo " '--with-ssl=/Users/bamboo/Desktop/harry/libsnowflakeclient/scripts/../deps-build/darwin/Release/openssl' '--without-nss' '--enable-static' '--disable-shared' '--prefix=/Users/bamboo/De
Paths include local fixed paths instead of relative paths to the base project directory.

2021-01-08 22:27 UTC, sfc-gh-vreddy commented on libsnowflakeclient/deps-build/darwin/aws/lib/cmake/aws-cpp-sdk-core/aws-cpp-sdk-core-targets.cmake
> +  INTERFACE_LINK_LIBRARIES "pthread;/Users/bamboo/Desktop/harry/libsnowflakeclient/scripts/../deps-build/darwin/Release/curl/lib"
I see the old files also has static paths? Are these files generated? Should they be in the repo at all?

2021-01-08 22:28 UTC, sfc-gh-vreddy requested changes
Paths include local fixed paths instead of relative paths to the base project directory. 
Are they generated files? Do they need to be in the repo at all?

2021-01-08 23:01 UTC, SimbaGithub commented
> Paths include local fixed paths instead of relative paths to the base project directory.
> Are they generated files? Do they need to be in the repo at all?

Those files are generated during the build process and I don't think they are necessary to build the driver. Will delete them.

2021-01-09 02:12 UTC, SimbaGithub commented
@sfc-gh-vreddy  Removed unnecessary files in libsnowflakeclient and test passed on local environment.

2021-01-11 19:10 UTC, sfc-gh-vreddy approved these changes
LGTM

2021-01-11 19:13 UTC, sfc-gh-vreddy commented
@sfc-gh-kwagner Could you take care of merging this.

2021-01-11 21:29 UTC, merged